version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=VALUE
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"    #new
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d 
      - ./nginx/certbot/www:/var/www/certbot/:ro  #new
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro  #new
    depends_on:
      - web
    restart: always

#new
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email ping001@fastapitutorial.com --agree-tos --no-eff-email -d despam.io
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw